version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: PT_GLOBAL_THINK_MONGO
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nestjs:
    build: .
    container_name: PT_GLOBAL_THINK
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/pt_global_think

volumes:
  mongodb_data:
